"""empty message

Revision ID: 1a0a2d524011
Revises: 31a367964d91
Create Date: 2015-07-08 03:52:06.159393

"""

# revision identifiers, used by Alembic.
revision = '1a0a2d524011'
down_revision = '31a367964d91'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'groups_captain_id_fkey', 'groups', type_='foreignkey')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'groups_captain_id_fkey', 'groups', 'students', ['captain_id'], ['id'])
    ### end Alembic commands ###
