"""empty message

Revision ID: 1b927e4ae563
Revises: 42c4a1806c7
Create Date: 2015-07-21 22:31:13.767022

"""

# revision identifiers, used by Alembic.
revision = '1b927e4ae563'
down_revision = '42c4a1806c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('photo', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'photo')
    ### end Alembic commands ###
