"""empty message

Revision ID: 1d4c18f8f404
Revises: 36cd85d3fb79
Create Date: 2016-08-22 21:45:05.931792

"""

# revision identifiers, used by Alembic.
revision = '1d4c18f8f404'
down_revision = '36cd85d3fb79'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('active_year', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    ### end Alembic commands ###
