"""empty message

Revision ID: 31a367964d91
Revises: 498a183d882
Create Date: 2015-07-08 03:48:41.410684

"""

# revision identifiers, used by Alembic.
revision = '31a367964d91'
down_revision = '498a183d882'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('captain_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'groups', 'students', ['captain_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'captain_id')
    ### end Alembic commands ###
