"""empty message

Revision ID: 36c07550adf6
Revises: 1b927e4ae563
Create Date: 2015-08-07 15:17:56.608146

"""

# revision identifiers, used by Alembic.
revision = '36c07550adf6'
down_revision = '1b927e4ae563'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labs', sa.Column('order', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labs', 'order')
    ### end Alembic commands ###
