"""empty message

Revision ID: 3e5c36615577
Revises: 77803dbc2285
Create Date: 2016-09-02 21:14:27.301405

"""

# revision identifiers, used by Alembic.
revision = '3e5c36615577'
down_revision = '77803dbc2285'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
