"""empty message

Revision ID: 4cc493d499fb
Revises: 6f95021e6bca
Create Date: 2017-12-11 01:50:26.209193

"""

# revision identifiers, used by Alembic.
revision = '4cc493d499fb'
down_revision = '6f95021e6bca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('ignore', sa.Boolean(), nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'ignore')
    # ### end Alembic commands ###
