"""empty message

Revision ID: 6f95021e6bca
Revises: 810b2e0ccf3c
Create Date: 2016-11-13 19:55:25.638852

"""

# revision identifiers, used by Alembic.
revision = '6f95021e6bca'
down_revision = '810b2e0ccf3c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('deleted', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'deleted')
    ### end Alembic commands ###
