"""empty message

Revision ID: 810b2e0ccf3c
Revises: 665b5c690659
Create Date: 2016-09-15 19:18:17.215328

"""

# revision identifiers, used by Alembic.
from alembic.ddl.base import alter_column

revision = '810b2e0ccf3c'
down_revision = '665b5c690659'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("disciplinefiles", "title", existing_type=sa.String(50), type_=sa.Text())
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("disciplinefiles", "title", existing_type=sa.Text(), type_=sa.String(50))
    ### end Alembic commands ###
