"""empty message

Revision ID: ba40557f3361
Revises: 4cc493d499fb
Create Date: 2018-01-13 19:16:34.753027

"""

# revision identifiers, used by Alembic.
revision = 'ba40557f3361'
down_revision = '4cc493d499fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('site_disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'site_disabled')
    # ### end Alembic commands ###
